### PR TITLE
Automated reformat of all the code with astyle formatting rules. 

### PR DESCRIPTION
**Pull request by rv0**
As discussed in https://github.com/HomoElectromagneticus/Yocto_808/issues/25
No changes in the actual code, just changes the formatting of everything

Used SublimeAStyleFormatter plugin for Sublime Text, hence also added the used project level configuration that has the specific astyle rules as discussed in the above-mentioned issue.

Would be glad to add other astyle config files for other editors if that is relevant.

### CODE REVIEW

**Comment by rv0** [comment]
Noticed today there's 2 minor things I should add:

Stuff like
```
if (step_count < 16 || step_count == 255)button_pattern_part = 0; //on initialise a 0 quand le pas courant est en dessous de 16 ou en mode stop soit step_count=255
else if (step_count >= 16)button_pattern_part = 1;`
```
is left untouched, I'd rather see it broken up with {}

also spaces in if ( bla ) are not removed 
```
if ( button_encoder == 1 && tap_button_shift == 0) {
}
```

So please don't merge yet, I'll update the astyle rules and this pull request when I find the time.

**Comment by HomoElectromagneticus** [comment]
Any update on this one? I was about to merge and compile this locally then diff the compiled sysex with the last release to see if they matched, but then I saw your "please don't merge yet" note. No rush of course, just checking in!

**Comment by rv0** [comment]
Postponed but not forgotten :)

**Comment by rv0** [comment]
Ok, updated the PR.. Addresses the above issues.
Still one thing that I couldn't figure out yet, in BPM_function.ino we have e.g.:
`tapTempo[ 0] = millis();`
I haven't figured out how to remove the space there. But that seems like a minor problem so if you agree on the other formatting changes I'd say its good to go.

**Comment by HomoElectromagneticus** [comment]
The binary compare came out clean, and the new source looks good!

**Pull request merged**
