### PR TITLE
Annoying slave sync issue in pattern edit

### PR DESCRIPTION
**Pull request by rv0**
This pull request was initially meant to fix an annoying issue when slaved in pattern edit mode: when you press stop on the master clock, pattern edit mode reverts back to internal clock and initial pattern, only way to go back is by changing the yocto to pattern play midi again, and selecting the pattern you had (if you remember where it was).
While testing the sync modes, many issues were discovered, so I decided to fix whatever came on my path:

To summarise:
- Circumvented the sync issue by changing the logic of mode switching. 
- Refactored the main loop so that all shared code between the modes is in one place.
- Bugfix: Midi to Dinsync conversion used a way too short pulsewidth, unusable with e.g. 606. Also it is not recommended to let midi callbacks "wait" (the sleep to create the pulsewidth). Added a 2nd Timer for to handle the Dinsync pulsewidth via interrupt. Had to change TimerOne to TimerOneThree library for this.
- Bugfix: When midi slaved, the yocto missed a clock tick after the first step because it re-initialised the ppqn counter. This probably caused a lot of headaches for people syncing the Yocto with external midi.
- Bugfix: when slaved to Dinsync, there was no check to see if dinsync was stopped (so if you were to stop the external master clock, the yocto would keep running).

Possible improvements:
- Track/Song modes are left untouched

### CODE REVIEW

**Comment by HomoElectromagneticus** [comment]
What prompted the change from the original 1ms post-run clock delay to 4ms and then finally 2ms?

**Comment by rv0** [comment]
> What prompted the change from the original 1ms post-run clock delay to 4ms and then finally 2ms?

1ms was not the post-run clock delay, but the actual length of the clock pulse, which is not enough for most if not all original dinsync devices.
A pulsewidth of 4ms is a safe value for dinsync in my experience, but using a blocking sleep of 4ms in the a midi callback is a very bad idea, so I removed that and implemented a timer based solution with and unused timer on the cpu (Timer3).
The 2ms you see there is a post-run clock delay. I have no research of my own regarding this, I just copy what Robin Whittle is doing on his TR-808 midi interface: http://www.firstpr.com.au/rwi/tr-808/TR-808-MIDI-In.pdf , quoted here:

> There is no formal specification for DIN/Roland Sync. One potential difficulty is if a device, such as a MIDI to DIN/Roland Sync converter, raises the Run/Stop signal and then, with little or no time delay, raises the Clock signal as part of the first clock pulse. Not every device is looking for the start of a clock pulse immediately after the rising edge of the Run/Stop signal. Unless special care is taken, a MIDI to DIN/Roland Sync converter might raise the Run/Stop signal, and then 1/3 millisecond later (MIDI involves 1/3ms between bytes) raises the Clock signal, then the slave device may not recognise this as the first clock pulse. Consequently, the slave device will run one clock pulse behind the rest of the system. The TR-808, TB-303 and TR-606 all require longer than this 1/3ms to start looking for the clock pulses. This interface (and likewise the MIDI system in the Devil Fish) is programmed to delay the first clock pulse for 2 milliseconds in order that the microcontrollers in these slave devices always has time after the rising edge of the Run/Stop signal to start looking for Clock pulses.

I could and probably should also use the timer for the 2ms delay, but there's also other places in the code that may benefit from a timer. It's the first time I ever used a timer so the idea still needs to grow in my head first ;)

**Comment by HomoElectromagneticus** [comment]
Okay, that makes sense. I'll merge and build this locally to test it this week. I noticed some weird behavior with the encoder and MIDI on my machine while testing the "all updates" sysex you posted on the e-licktronic forums.  My guess is that the Tap Write feature branch is causing it, but I want to be sure before we merge either Tap Write or this branch with master. Especially now that the new MIDI library is in master.

**Comment by rv0** [comment]
It would be better to merge the Tap write first, as there's changes in the manual for pattern edit mode. This pull request also needs changes to explain how the sync changes interact with it, so it will be a pain to merge it otherwise.
Also I'd like to change the 2ms delayed clock to also use the timer, and check for some of the weird consequences (e.g. changing bank / pattern in edit mode only possible when clock is stopped, but not sure if it works for all sync modes.

**Comment by rv0** [comment]
When the yocto is just booted in EDIT mode, it is not possible to start it without first starting in one of the play modes. This needs to be clarified in the manual, but a fallback to internal sync would be nice.

**Comment by HomoElectromagneticus** [comment]
Timing the 2ms delay with a timer would be best, I agree. However, that shouldn't hold up the code from being merged with master if existing methods of timing that pulse are reliable.

After testing this code however, there are issues that I think should prevent it from being merged with master. It looks like this code introduces an issue with the encoder where you have to turn it _a lot_ in order to change the tempo by a reasonable amount. Additionally, the regression of not being able to start while in Pattern Edit mode seems bad.

With respect to the encoder behavior, the existing code uses Timer1 to set the BPM together with the change in encoder state. It's not immediately obvious how your change to the Timers could affect the encoder response...

**Comment by rv0** [comment]
- encoder issue: **bug** that must be fixed indeed, cant believe i missed that, clueless atm though
- start in edit mode regression: **fixed** introduced sync_fallback variable. basically it stores in which sync mode "start" was pressed and defaults to master sync. This works _really_ intuitive now imo
build: [yocto.syx.txt](https://github.com/HomoElectromagneticus/Yocto_808/files/2912347/yocto.syx.txt)

**Comment by rv0** [comment]
fixed the tempo / timer issue:
[yocto.syx.txt](https://github.com/HomoElectromagneticus/Yocto_808/files/2912570/yocto.syx.txt)

**Comment by rv0** [comment]
Added the timer for the delayed dinsync clock pulse. 
[yocto.syx.txt](https://github.com/HomoElectromagneticus/Yocto_808/files/2912620/yocto.syx.txt)
I think everything is ok now.

**Comment by HomoElectromagneticus** [comment]
Just ran this build through its paces. Looks great!

**Pull request merged**
